language: node_js
node_js:
  #- '5.1'
  - '4.2'
  - 'iojs'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm install -g standard
  - npm install -g mocha

after_script:
  - sh build.sh # This is temporary!
